### ISSUE TITLE
Clarification on AddNode

### ISSUE THREAD

**Issue by 89z** [paultag/go-topsort#9] opened 2021-04-25 13:56 UTC
I am trying to use topsort with the output from Golang callgraph [1], which is like this:

~~~
"prog/test.A" "prog/test.C"
"prog/test.A" "prog/test.D"
"prog/test.main" "prog/test.A"
"prog/test.B" "prog/test.E"
"prog/test.B" "prog/test.F"
"prog/test.main" "prog/test.B"
~~~

As a test, I can use this program [2] and it works as expected. However, I am not going to know all the nodes until the end. My question is, what is the point of `AddNode`? With most DAG input I have seen, you dont get a listing of the nodes, but just a listing of edges. So isnt `AddNode` redundant, or something that could be processed internally?

1. https://github.com/golang/tools/tree/master/cmd/callgraph
2. https://github.com/paultag/go-topsort#example

**Comment by paultag** [comment] 2021-04-25 14:22
@89z this was designed when I needed to sort the dependency graph of debs in the archive. I was doing two big things -- which was associating other data with the node, as well as being able to handle packages that had no dependency edges.

This is easy enough to do. There's now a `AddEdgeAndNodes` helper that will create nodes with a nil data member if no such node already exists. This is tagged as `v0.1.1`

Here's the test case I checked in with it

```
func TestTopsortEasyEdges(t *testing.T) {
       network := topsort.NewNetwork()
       network.AddEdgeAndNodes("foo", "bar")
       series, err := network.Sort()
       isok(t, err)
       assert(t, len(series) == 2)
}
```

**Closed by paultag** 2021-04-25 14:22 UTC

**Comment by paultag** [comment] 2021-04-25 14:24
The API is kinda jacked as I'm looking at it -- heck, this was from 2015, we've grown a lot as a community since then and there's likely some cleanup that i could do here. This package is used as a dependency in a few places, but I haven't sunk a bunch of time into cleanup here -- but I'd be happy to.

**Comment by 89z** [comment] 2021-04-25 14:29
Ive been looking at different topological sort options, as Go doesnt seem to have any official one. I wouldnt want you to put a lot of time into cleanup, unless you just want to. I havent decided what package to go with yet. I havent seen many that offer "edge only" approach though, so now that this one does, its looking good!

**Comment by paultag** [comment] 2021-04-25 14:36
@89z I have some "this is for recreational go" time set aside, I just spend it differently depending on the day. Having consumers does help with ordering :)

**Comment by 89z** [comment] 2021-04-25 14:40
well if it matters, these are the other ones I have found so far, that seem to do what I need:

- https://github.com/amwolff/gorder
- https://github.com/gammazero/toposort
- https://github.com/yashbhutwala/go-directed-acyclic-graph
